### ISSUE TITLE
Session factory 

### ISSUE THREAD

**Issue by pavan7044** [pavan7044/KUMAR7044#4]

**Comment by sandhyasri-git** [comment]
What is the problem with Sessionfactory? 
State the issue clearly.

**Comment by pavan7044** [comment]
CREATE BEAN WITH -SESSION FACTORY ERROR:

**Comment by pavan7044** [comment]
You map your dispatcher to  *.do:
<servlet-mapping>
   <servlet-name>Dispatcher</servlet-name>
   <url-pattern>*.do</url-pattern>
</servlet-mapping>
but your controller is mapped on an url without .do:
@RequestMapping("/editPresPage")
Try changing this to:
@RequestMapping("/editPresPage.do")

**Comment by pavan7044** [comment]
Mam there is an any other solution to rectify the session factory error
